//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        public int IdLibro { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdBiblioteca { get; set; }
    
        public virtual Biblioteca Biblioteca { get; set; }
    }
}
